google_defaults: &google_defaults
  scopes: [userinfo.email, userinfo.profile]
  glass_scopes: [userinfo.email, userinfo.profile, glass.timeline]
development:
  client_id: ENV[:GOOGLE_KEY]
  client_secret: ENV[:GOOGLE_SECRET]
  <<: *google_defaults
test:
  client_id: ENV[:GOOGLE_KEY]
  client_secret: ENV[:GOOGLE_SECRET]
  <<: *google_defaults
production:
  client_id: ENV[:GOOGLE_KEY]
  client_secret: ENV[:GOOGLE_SECRET]
  <<: *google_defaults
